export {
  fetchDiscoveryFacets,
  fetchSearchStrategies,
  searchPortal,
  searchPortalSequences,
  searchPortalStructured,
  type DiscoveryFacetValue,
  type DiscoveryFacets,
  type DiscoverySort,
  type PortalSearchHit,
  type PortalSearchQuery,
  type PortalSearchResponse,
  type SearchStrategiesResponse,
  type SearchStrategyDescriptor,
  type SequenceSearchHit,
  type SequenceSearchResponse,
  type SortDirection,
  type StructuredFilterKind,
  type StructuredSearchHit,
  type StructuredSearchInputKind,
  type StructuredSearchQuery,
  type StructuredSearchRequest,
  type StructuredSearchResponse,
  type StructuredSearchTotal,
} from "@/features/registry/api";
