//! Backend-neutral collection-content validators and conditional-write types.
//!
//! A synchronized collection contains both biological SBOL data and
//! server-managed collaboration evidence in the same named graph. The remote
//! content ETag deliberately hashes only the former, so sharing, reviews, audit
//! events, and server timestamps do not create false synchronization conflicts.

use std::collections::BTreeSet;

use sbol_db_core::{ObjectTerm, SubjectTerm, Triple};
use sha2::{Digest, Sha256};

use crate::{SBH_CAN_VIEW, SBH_OWNED_BY};

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const DCTERMS_CREATED: &str = "http://purl.org/dc/terms/created";
const DCTERMS_MODIFIED: &str = "http://purl.org/dc/terms/modified";
const SBH_TOP_LEVEL: &str = "http://wiki.synbiohub.org/wiki/Terms/synbiohub#topLevel";
const AUDIT_EVENT_TYPE: &str = "https://sbol-db.org/terms#AuditEvent";
const ADMIN_AUDIT_EVENT_TYPE: &str = "https://sbol-db.org/terms#AdminAuditEvent";

/// Result of an atomic create-or-compare-and-swap collection-content write.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ConditionalContentWrite {
    Applied {
        triple_count: usize,
        content_etag: String,
    },
    PreconditionFailed {
        current_content_etag: Option<String>,
    },
}

/// Compute the opaque, representation-independent validator for a collection's
/// biological content. Graph names and server-managed triples are excluded.
pub fn collection_content_etag(triples: &[Triple]) -> Option<String> {
    let content = biological_content(triples);
    if content.is_empty() {
        return None;
    }

    let mut rows = content.iter().map(triple_key).collect::<Vec<_>>();
    rows.sort();
    rows.dedup();
    let mut digest = Sha256::new();
    for row in rows {
        digest.update((row.len() as u64).to_be_bytes());
        digest.update(row);
    }
    Some(format!(
        "\"sbol-content-v1-{}\"",
        hex::encode(digest.finalize())
    ))
}

/// Return the biological part of a collection graph, with graph ownership
/// removed so it can be serialized as a regular SBOL document.
pub fn biological_content(triples: &[Triple]) -> Vec<Triple> {
    let audit_subjects = audit_subjects(triples);
    triples
        .iter()
        .filter(|triple| !is_server_managed(triple, &audit_subjects))
        .cloned()
        .map(|mut triple| {
            triple.graph_iri = None;
            triple
        })
        .collect()
}

/// Extract server-managed triples from a trusted, server-generated graph. This
/// is used by initial submission minting so biological content and ownership
/// stamps enter the atomic create primitive through separate trust channels.
pub fn server_managed_content(triples: &[Triple]) -> Vec<Triple> {
    let audit_subjects = audit_subjects(triples);
    triples
        .iter()
        .filter(|triple| is_server_managed(triple, &audit_subjects))
        .cloned()
        .map(|mut triple| {
            triple.graph_iri = None;
            triple
        })
        .collect()
}

/// Compose a replacement graph from untrusted submitted content plus the
/// server-managed evidence already attached to the live graph. Incoming
/// ownership, sharing, timestamps, and audit subjects are discarded.
pub fn replacement_graph(current: &[Triple], incoming: &[Triple], graph: &str) -> Vec<Triple> {
    replacement_graph_with_management(current, incoming, &[], graph)
}

/// Compose a replacement and add management triples generated by a trusted
/// application service. Unlike `incoming`, this slice is not filtered: it is
/// how authenticated ownership is stamped on newly synchronized subjects.
pub fn replacement_graph_with_management(
    current: &[Triple],
    incoming: &[Triple],
    server_managed: &[Triple],
    graph: &str,
) -> Vec<Triple> {
    let current_audit_subjects = audit_subjects(current);
    let incoming_audit_subjects = audit_subjects(incoming);
    let live_subjects = incoming
        .iter()
        .filter(|triple| !is_server_managed(triple, &incoming_audit_subjects))
        .map(subject_key)
        .collect::<BTreeSet<_>>();
    let graph = sbol_db_core::IriString::unchecked(graph.to_owned());

    let mut replacement = current
        .iter()
        .filter(|triple| {
            if !is_server_managed(triple, &current_audit_subjects) {
                return false;
            }
            // Sharing and immutable audit evidence survive independently of
            // the biological subjects in the new document. Per-subject stamps
            // survive only while that subject remains, preventing a full sync
            // from leaving orphan ownership or top-level marker triples.
            current_audit_subjects.contains(&subject_key(triple))
                || triple.predicate.as_str() == SBH_CAN_VIEW
                || live_subjects.contains(&subject_key(triple))
        })
        .cloned()
        .collect::<Vec<_>>();
    replacement.extend(
        incoming
            .iter()
            .filter(|triple| !is_server_managed(triple, &incoming_audit_subjects))
            .cloned(),
    );
    replacement.extend(server_managed.iter().cloned());
    for triple in &mut replacement {
        triple.graph_iri = Some(graph.clone());
    }
    replacement.sort_by_key(triple_key);
    replacement.dedup();
    replacement
}

fn subject_key(triple: &Triple) -> String {
    match &triple.subject {
        SubjectTerm::Iri(subject) => subject.as_str().to_owned(),
        SubjectTerm::BlankNode(subject) => format!("_:{subject}"),
    }
}

fn audit_subjects(triples: &[Triple]) -> BTreeSet<String> {
    triples
        .iter()
        .filter_map(|triple| {
            if triple.predicate.as_str() != RDF_TYPE {
                return None;
            }
            let ObjectTerm::Iri(kind) = &triple.object else {
                return None;
            };
            if !matches!(kind.as_str(), AUDIT_EVENT_TYPE | ADMIN_AUDIT_EVENT_TYPE) {
                return None;
            }
            match &triple.subject {
                SubjectTerm::Iri(subject) => Some(subject.as_str().to_owned()),
                SubjectTerm::BlankNode(subject) => Some(format!("_:{subject}")),
            }
        })
        .collect()
}

fn is_server_managed(triple: &Triple, audit_subjects: &BTreeSet<String>) -> bool {
    let predicate = triple.predicate.as_str();
    if matches!(
        predicate,
        SBH_OWNED_BY | SBH_CAN_VIEW | SBH_TOP_LEVEL | DCTERMS_CREATED | DCTERMS_MODIFIED
    ) {
        return true;
    }
    let subject = match &triple.subject {
        SubjectTerm::Iri(subject) => subject.as_str(),
        SubjectTerm::BlankNode(subject) => return audit_subjects.contains(&format!("_:{subject}")),
    };
    audit_subjects.contains(subject)
}

fn triple_key(triple: &Triple) -> Vec<u8> {
    let mut key = Vec::new();
    match &triple.subject {
        SubjectTerm::Iri(value) => {
            key.push(b'I');
            push_field(&mut key, value.as_str());
        }
        SubjectTerm::BlankNode(value) => {
            key.push(b'B');
            push_field(&mut key, value);
        }
    }
    push_field(&mut key, triple.predicate.as_str());
    match &triple.object {
        ObjectTerm::Iri(value) => {
            key.push(b'I');
            push_field(&mut key, value.as_str());
        }
        ObjectTerm::BlankNode(value) => {
            key.push(b'B');
            push_field(&mut key, value);
        }
        ObjectTerm::Literal {
            value,
            datatype,
            language,
        } => {
            key.push(b'L');
            push_field(&mut key, value);
            push_field(&mut key, datatype.as_str());
            push_field(&mut key, language.as_deref().unwrap_or(""));
        }
    }
    key
}

fn push_field(buffer: &mut Vec<u8>, value: &str) {
    buffer.extend_from_slice(&(value.len() as u64).to_be_bytes());
    buffer.extend_from_slice(value.as_bytes());
}

#[cfg(test)]
mod tests {
    use sbol_db_core::{IriString, ObjectTerm, SubjectTerm, Triple};

    use super::*;

    fn iri(value: &str) -> IriString {
        IriString::unchecked(value.to_owned())
    }

    fn triple(subject: &str, predicate: &str, object: &str) -> Triple {
        Triple {
            graph_iri: Some(iri("https://sbol.io/user/alice/toggle/toggle_collection/1")),
            subject: SubjectTerm::Iri(iri(subject)),
            predicate: iri(predicate),
            object: ObjectTerm::Iri(iri(object)),
        }
    }

    #[test]
    fn collaboration_and_audit_data_do_not_change_content_etag() {
        let design = triple("urn:design", RDF_TYPE, "http://sbols.org/v2#Collection");
        let original = collection_content_etag(std::slice::from_ref(&design)).unwrap();
        let mut enriched = vec![design];
        enriched.push(triple("urn:design", SBH_OWNED_BY, "urn:user:alice"));
        enriched.push(triple("urn:user:alice", SBH_CAN_VIEW, "urn:design"));
        enriched.push(triple("urn:audit", RDF_TYPE, AUDIT_EVENT_TYPE));
        enriched.push(triple(
            "urn:audit",
            "https://sbol-db.org/terms#auditAction",
            "urn:action",
        ));
        assert_eq!(collection_content_etag(&enriched).unwrap(), original);
    }

    #[test]
    fn biological_changes_produce_a_new_etag() {
        let original = vec![triple(
            "urn:design",
            RDF_TYPE,
            "http://sbols.org/v2#Collection",
        )];
        let mut changed = original.clone();
        changed.push(triple(
            "urn:design",
            "http://sbols.org/v2#member",
            "urn:component",
        ));
        assert_ne!(
            collection_content_etag(&original),
            collection_content_etag(&changed)
        );
    }

    #[test]
    fn replacement_preserves_live_management_and_rejects_submitted_management() {
        let live_owner = triple("urn:design", SBH_OWNED_BY, "urn:user:alice");
        let incoming_owner = triple("urn:design", SBH_OWNED_BY, "urn:user:mallory");
        let design = triple("urn:design", RDF_TYPE, "http://sbols.org/v2#Collection");
        let replacement = replacement_graph(
            std::slice::from_ref(&live_owner),
            &[incoming_owner, design],
            "urn:graph",
        );
        assert!(replacement
            .iter()
            .any(|value| value.object == live_owner.object));
        assert!(!replacement.iter().any(|value| {
            matches!(&value.object, ObjectTerm::Iri(iri) if iri.as_str() == "urn:user:mallory")
        }));
        assert!(replacement
            .iter()
            .all(|value| value.graph_iri.as_ref().unwrap().as_str() == "urn:graph"));
    }
}
