import {
  CalendarClock,
  ExternalLink,
  FileClock,
  Globe2,
  LockKeyhole,
  UserRound,
} from "lucide-react";

import { ObjectSection } from "@/components/portal/ObjectSection";
import { Badge } from "@/components/ui/badge";
import type { PortalObjectDetails } from "@/features/portal/api";
import { shortIri } from "@/features/portal/format";

export function ObjectProvenance({ object }: { object: PortalObjectDetails }) {
  const provenance = object.provenance;
  const hasDetailedProvenance =
    provenance.creators.length > 0 ||
    provenance.derived_from.length > 0 ||
    provenance.generated_by.length > 0 ||
    provenance.mutable_source.length > 0 ||
    provenance.citations.length > 0;

  return (
    <ObjectSection
      id="provenance"
      icon={FileClock}
      title="Ownership and provenance"
      description="Where this object is stored, who owns it, and the provenance assertions carried with it."
    >
      <dl className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Fact
          icon={object.visibility === "public" ? Globe2 : LockKeyhole}
          label="Visibility"
          value={object.visibility === "public" ? "Public" : "Restricted"}
        />
        <Fact
          icon={UserRound}
          label="Owners"
          value={
            object.owners.length > 0
              ? object.owners.map(shortIri).join(", ")
              : "Not asserted"
          }
          title={object.owners.join("\n")}
        />
        <Fact
          icon={CalendarClock}
          label="Created"
          value={formatTimestamp(object.created_at)}
          title={object.created_at || undefined}
        />
        <Fact
          icon={CalendarClock}
          label="Modified"
          value={formatTimestamp(object.modified_at)}
          title={object.modified_at || undefined}
        />
      </dl>

      <div className="mt-5 rounded-xl border bg-muted/10 p-4">
        <div className="text-xs font-medium text-muted-foreground">
          Source graph
        </div>
        <code className="mt-1.5 block break-all font-mono text-xs leading-5">
          {object.source_graph || "No named source graph"}
        </code>
      </div>

      {hasDetailedProvenance ? (
        <div className="mt-5 grid gap-5 border-t pt-5 sm:grid-cols-2">
          <ValueList label="Creators" values={provenance.creators} />
          <ValueList label="Derived from" values={provenance.derived_from} />
          <ValueList label="Generated by" values={provenance.generated_by} />
          <ValueList
            label="Registry provenance"
            values={provenance.mutable_source}
          />
          <Citations values={provenance.citations} />
        </div>
      ) : (
        <p className="mt-5 border-t pt-5 text-sm text-muted-foreground">
          No creator, derivation, generation, registry provenance, or citation
          values are asserted.
        </p>
      )}
    </ObjectSection>
  );
}

function Fact({
  icon: Icon,
  label,
  value,
  title,
}: {
  icon: typeof Globe2;
  label: string;
  value: string;
  title?: string;
}) {
  return (
    <div className="rounded-xl border bg-card p-3.5">
      <dt className="flex items-center gap-2 text-xs font-medium text-muted-foreground">
        <Icon className="size-3.5" aria-hidden="true" /> {label}
      </dt>
      <dd className="mt-2 truncate text-sm font-medium" title={title}>
        {value}
      </dd>
    </div>
  );
}

function ValueList({ label, values }: { label: string; values: string[] }) {
  return (
    <div>
      <h3 className="text-xs font-medium uppercase tracking-[0.1em] text-muted-foreground">
        {label}
      </h3>
      {values.length > 0 ? (
        <ul className="mt-2 space-y-1.5">
          {values.map((value) => (
            <li
              key={value}
              className="break-words rounded-lg bg-muted/35 px-3 py-2 text-sm leading-5"
              title={value}
            >
              {safeUrl(value) ? (
                <a
                  href={value}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-start gap-1.5 text-primary hover:underline"
                >
                  <span className="break-all">{shortIri(value)}</span>
                  <ExternalLink className="mt-0.5 size-3 shrink-0" />
                </a>
              ) : (
                value
              )}
            </li>
          ))}
        </ul>
      ) : (
        <p className="mt-2 text-sm text-muted-foreground">Not asserted</p>
      )}
    </div>
  );
}

function Citations({ values }: { values: string[] }) {
  if (values.length === 0) return null;
  return (
    <div className="sm:col-span-2">
      <h3 className="text-xs font-medium uppercase tracking-[0.1em] text-muted-foreground">
        Citations
      </h3>
      <div className="mt-2 flex flex-wrap gap-2">
        {values.map((value) => {
          const pubmed = /^\d+$/.test(value)
            ? `https://pubmed.ncbi.nlm.nih.gov/${value}/`
            : null;
          const badge = (
            <Badge
              variant="secondary"
              className="gap-1.5 font-mono text-[10px]"
            >
              {/^[0-9]+$/.test(value) ? "PMID" : "Citation"} {value}
              {pubmed && <ExternalLink className="size-3" />}
            </Badge>
          );
          return pubmed ? (
            <a
              key={value}
              href={pubmed}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            >
              {badge}
            </a>
          ) : (
            <span key={value}>{badge}</span>
          );
        })}
      </div>
    </div>
  );
}

function formatTimestamp(value: string | null): string {
  if (!value) return "Not asserted";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}

function safeUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}
