//! Criterion benchmarks for the k-mer index hot paths. Catches regressions
//! in the sliding-window iterator (especially the reprime branch after an
//! ambiguous base) and in the per-base table lookups.

use criterion::{black_box, criterion_group, criterion_main, Criterion, Throughput};
use sbol_db_core::kmer::{canonical_kmers, encode_kmer, reverse_complement_string, KMER_K};

/// Deterministic ACGT string of `len` bytes generated by a simple LCG. Bench
/// inputs need to be reproducible across runs so reported numbers compare.
fn acgt(len: usize, seed: u64) -> String {
    let mut s = String::with_capacity(len);
    let alphabet = b"ACGT";
    let mut x = seed | 1;
    for _ in 0..len {
        x = x
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        s.push(alphabet[(x >> 33) as usize & 0b11] as char);
    }
    s
}

/// ACGT string with `N` injected every `period` positions. Smaller `period`
/// forces more reprimes in the sliding-window iterator.
fn acgt_with_n(len: usize, seed: u64, period: usize) -> String {
    let mut s = acgt(len, seed).into_bytes();
    for i in (period - 1..s.len()).step_by(period) {
        s[i] = b'N';
    }
    String::from_utf8(s).unwrap()
}

fn bench_canonical_kmers(c: &mut Criterion) {
    let mut group = c.benchmark_group("canonical_kmers");

    let clean = acgt(1_000_000, 0xCAFE);
    group.throughput(Throughput::Bytes(clean.len() as u64));
    group.bench_function("clean_1MB", |b| {
        b.iter(|| {
            let mut count = 0usize;
            for h in canonical_kmers(black_box(&clean)) {
                black_box(h.canonical);
                count += 1;
            }
            count
        })
    });

    // N every 50 bases: rare reprime — primed branch dominates.
    let sparse_n = acgt_with_n(1_000_000, 0xCAFE, 50);
    group.throughput(Throughput::Bytes(sparse_n.len() as u64));
    group.bench_function("n_every_50_1MB", |b| {
        b.iter(|| canonical_kmers(black_box(&sparse_n)).count())
    });

    // N every 9 bases: every window contains an N, so we never get past
    // priming — exercises only the unprimed branch and the restart logic.
    let dense_n = acgt_with_n(1_000_000, 0xCAFE, 9);
    group.throughput(Throughput::Bytes(dense_n.len() as u64));
    group.bench_function("n_every_9_1MB", |b| {
        b.iter(|| canonical_kmers(black_box(&dense_n)).count())
    });

    group.finish();
}

fn bench_reverse_complement_string(c: &mut Criterion) {
    let s = acgt(1_000_000, 0xBEEF);
    let mut group = c.benchmark_group("reverse_complement_string");
    group.throughput(Throughput::Bytes(s.len() as u64));
    group.bench_function("1MB", |b| {
        b.iter(|| reverse_complement_string(black_box(&s)))
    });
    group.finish();
}

fn bench_encode_kmer(c: &mut Criterion) {
    let strings: Vec<String> = (0..1_000_000)
        .map(|i| {
            let s = acgt(KMER_K, 0xF00D ^ i as u64);
            assert_eq!(s.len(), KMER_K);
            s
        })
        .collect();
    let mut group = c.benchmark_group("encode_kmer");
    group.throughput(Throughput::Elements(strings.len() as u64));
    group.bench_function("1M_random_8base", |b| {
        b.iter(|| {
            let mut acc = 0u64;
            for s in &strings {
                acc = acc.wrapping_add(encode_kmer(black_box(s)).unwrap() as u64);
            }
            acc
        })
    });
    group.finish();
}

criterion_group!(
    benches,
    bench_canonical_kmers,
    bench_reverse_complement_string,
    bench_encode_kmer
);
criterion_main!(benches);
